### ISSUE TITLE
Documentation on how to make changes

### ISSUE THREAD

**Issue by JosephKJ** [lab1055/lab1055.github.io#3]
It would be nice to have documentation on how to

- Add new news
- Add new publication
- Manage group members
- (... other capabilities that I have missed ...)

**Comment by acl21** [comment]
Great idea Joseph. I will create a "How To" markdown with all the details. 

Also, I am thinking of asking the members of the group to raise a pull request for their changes like adding a news item or a publication. What do you think is better for the students and the website maintainer? Raising an issue or a pull request? Please share what you think.

**Comment by JosephKJ** [comment]
Raising a pull request if he/she knows how to do it would be ideal. You can give these steps on the 'How to' that you mentioned. Website maintainer should ideally not be bugged with all these.

**Comment by acl21** [comment]
That is exactly what I thought. Thank you. 

Keeping this issue open until documentation is added. 👍

**Comment by acl21** [comment]
@JosephKJ, you can find the tutorials on how to add news, publications, project pages, etc. on [how_to_add.md](https://github.com/lab1055/lab1055.github.io/blob/master/how_to_add.md) page now.
